# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-16 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('age', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
