# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181105_1208'),
    ]

    operations = [
        migrations.CreateModel(
            name='schemes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=50)),
                ('scheme_id', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('for_category', models.CharField(max_length=20)),
                ('income_criteria', models.DecimalField(decimal_places=2, default=50000, max_digits=20)),
                ('percentage_criteria', models.DecimalField(decimal_places=2, default=0, max_digits=2)),
            ],
        ),
    ]
