# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_schemes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='schemes',
            new_name='scheme',
        ),
    ]
