# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-05 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181105_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='max_graduation',
            new_name='educational_qualification',
        ),
    ]
