# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-06 06:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181105_2037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Details',
        ),
    ]
