# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-07 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20181106_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='grant_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='details',
            name='percentage_disabliity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='percentage_criteria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
