# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181107_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('scheme_name', models.CharField(max_length=50)),
                ('scheme_id', models.DecimalField(decimal_places=0, default=0, max_digits=5)),
                ('age', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('aadhar_id', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('category', models.CharField(max_length=20)),
                ('income', models.DecimalField(decimal_places=2, default=50000, max_digits=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('qualification', models.CharField(max_length=50, null=True)),
                ('ward_number', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('house_number', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('village', models.CharField(max_length=50, null=True)),
                ('user_id', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
