# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_id',
            new_name='for_category',
        ),
        migrations.AddField(
            model_name='application',
            name='grant_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='application',
            name='income_criteria',
            field=models.DecimalField(decimal_places=2, default=50000, max_digits=20),
        ),
        migrations.AddField(
            model_name='application',
            name='percentage_criteria',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
